<?php
require_once($_SERVER['DOCUMENT_ROOT']."/pp/includes/config.php");
require_once(LIB_PATH."log.php");
require_once(LIB_PATH."database.php");
require_once(LIB_PATH."databaseObject.php");
require_once(LIB_PATH."user.php");
require_once(LIB_PATH."admin.php");
require_once(LIB_PATH."session.php");
require_once(LIB_PATH."file.php");
require_once(LIB_PATH."functions.php");
